services:
    backend:
        build:
            context: ./songkran-online-api
            dockerfile: Dockerfile
        container_name: songkran-backend
        restart: always
        env_file:
            - ./songkran-online-api/.env
        ports:
            - '4000:4000'
        networks:
            - songkran-network
        depends_on:
            - db

    db:
        image: postgres:16-alpine
        container_name: songkran-db
        restart: always
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=songkran-online
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        networks:
            - songkran-network

networks:
    songkran-network:
        driver: bridge

volumes:
    postgres_data:
